In [13]:
from tensorflow.keras.utils import to_categorical
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from tensorflow.keras.regularizers import l1
import numpy as np

%matplotlib inline
seed = 0
np.random.seed(seed)
import tensorflow as tf

tf.random.set_seed(seed)
import os

data = fetch_openml('hls4ml_lhc_jets_hlf')
X, y = data['data'], data['target']


le = LabelEncoder()
y = le.fit_transform(y)
y = to_categorical(y, 5)
X_train_val, X_test, y_train_val, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(y[:5])
scaler = StandardScaler()
X_train_val = scaler.fit_transform(X_train_val)
X_test = scaler.transform(X_test)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l1
from callbacks import all_callbacks
model = Sequential()
model.add(Dense(64, input_shape=(16,), name='fc1', kernel_initializer='lecun_uniform', kernel_regularizer=l1(0.0001)))
model.add(Activation(activation='relu', name='relu1'))
model.add(Dense(32, name='fc2', kernel_initializer='lecun_uniform', kernel_regularizer=l1(0.0001)))
model.add(Activation(activation='relu', name='relu2'))
model.add(Dense(32, name='fc3', kernel_initializer='lecun_uniform', kernel_regularizer=l1(0.0001)))
model.add(Activation(activation='relu', name='relu3'))
model.add(Dense(5, name='output', kernel_initializer='lecun_uniform', kernel_regularizer=l1(0.0001)))
model.add(Activation(activation='softmax', name='softmax'))


train = True
if train:
    adam = Adam(learning_rate=0.0001)
    model.compile(optimizer=adam, loss=['categorical_crossentropy'], metrics=['accuracy'])

    model.fit(
        X_train_val,
        y_train_val,
        batch_size=1024,
        epochs=10,
        validation_split=0.25,
        shuffle=True,
    )
else:
    from tensorflow.keras.models import load_model

    model = load_model('model_1/KERAS_check_best_model.h5')

import plotting
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score

y_keras = model.predict(X_test)
print("Accuracy: {}".format(accuracy_score(np.argmax(y_test, axis=1), np.argmax(y_keras, axis=1))))


[[1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]]


/home/shakeel/Desktop/ML/hls4ml-env/lib/python3.12/site-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/10
487/487 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.4004 - loss: 1.5233 - val_accuracy: 0.6207 - val_loss: 1.1381
Epoch 2/10
487/487 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6397 - loss: 1.0998 - val_accuracy: 0.6806 - val_loss: 1.0101
Epoch 3/10
487/487 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6875 - loss: 0.9889 - val_accuracy: 0.7065 - val_loss: 0.9380
Epoch 4/10
487/487 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7100 - loss: 0.9243 - val_accuracy: 0.7188 - val_loss: 0.8927
Epoch 5/10
487/487 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7199 - loss: 0.8845 - val_accuracy: 0.7242 - val_loss: 0.8675
Epoch 6/10
487/487 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7243 - loss: 0.8624 - val_accuracy: 0.7272 - val_loss: 0.8524
Epoch 7/10
487/487 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7272 - loss: 0.8485 - val_accuracy: 0.7294 - val_loss: 0.8417
Epoch 8/10
487/487 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7294 - loss: 0.8384 - val_accuracy: 0.